services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  web:
    build: .
    image: tracking:0.0.1-SNAPSHOT
    ports:
      - 8081:8080
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
volumes:
  db_data:
